import { NFT, User } from './types';

export const MOCK_USER: User = {
  address: 'EQA...User',
  balance: 124.5,
  username: 'Nka_arm',
  avatar: 'https://picsum.photos/200/200?random=user',
  totalVolume: 1540,
  bought: 12,
  sold: 45
};

export const MOCK_NFTS: NFT[] = [
  {
    id: '1',
    title: 'Cyber Ape #1247',
    subtitle: '#001',
    description: 'Редкий представитель коллекции Cyber Apes с уникальным золотым шлемом и лазерными глазами. Один из 50 в коллекции.',
    price: 12.5,
    currency: 'TON',
    image: '/images/1.jpg',
    owner: 'EQC...A1b',
    verified: true,
    views: 1250,
    bids: 15,
    collection: 'Cyber Apes',
    model: 'Legendary',
    backdrop: 'Neon City'
  },
  {
    id: '2',
    title: 'Meta Punk #892',
    subtitle: '#002',
    description: 'OG Meta Punk с редким атрибутом "3D Glasses". Входит в топ-100 по редкости в коллекции из 10,000.',
    price: 8.3,
    currency: 'TON',
    image: '/images/2.jpg',
    owner: 'EQC...B2c',
    verified: true,
    views: 890,
    bids: 12,
    collection: 'Meta Punks',
    model: 'Epic',
    backdrop: 'Digital Grid'
  },
  {
    id: '3',
    title: 'TON Diamond #456',
    subtitle: '#003',
    description: 'Эксклюзивный NFT из официальной коллекции TON Foundation. Даёт доступ к закрытым ивентам экосистемы.',
    price: 5.7,
    currency: 'TON',
    image: '/images/3.jpg',
    owner: 'EQA...k2p',
    verified: true,
    views: 650,
    bids: 8,
    collection: 'TON Diamonds',
    model: 'Rare',
    backdrop: 'Crystal Cave'
  },
  {
    id: '4',
    title: 'Bored Whale #2891',
    subtitle: '#004',
    description: 'Культовый Bored Whale с золотой кожей и лазерными глазами. Менее 1% коллекции имеют оба атрибута.',
    price: 25.0,
    currency: 'TON',
    image: '/images/4.jpg',
    owner: 'EQD...j4L',
    verified: true,
    views: 2100,
    bids: 28,
    collection: 'Bored Whales',
    model: 'Legendary',
    backdrop: 'Deep Ocean'
  },
  {
    id: '5',
    title: 'Pixel Cat #1337',
    subtitle: '#005',
    description: 'Легендарный Pixel Cat из первого минта. Номер 1337 — культовый в крипто-сообществе.',
    price: 15.8,
    currency: 'TON',
    image: '/images/5.jpg',
    owner: 'EQF...p9q',
    verified: true,
    views: 1450,
    bids: 19,
    collection: 'Pixel Cats',
    model: 'Epic',
    backdrop: 'Retro Game'
  },
  {
    id: '6',
    title: 'Mutant Serum #001',
    subtitle: '#006',
    description: 'Genesis Mutant Serum — первый в коллекции. Использован для создания Mutant Ape. Исторический артефакт.',
    price: 32.0,
    currency: 'TON',
    image: '/images/6.jpg',
    owner: 'EQG...q1r',
    verified: true,
    views: 3200,
    bids: 42,
    collection: 'Mutant Lab',
    model: 'Mythic',
    backdrop: 'Laboratory'
  },
  {
    id: '7',
    title: 'Degen Doge #777',
    subtitle: '#007',
    description: 'Lucky Degen Doge с тройной семёркой. Холдеры получают airdrop от партнёрских проектов.',
    price: 28.5,
    currency: 'TON',
    image: '/images/7.jpg',
    owner: 'EQH...r2s',
    verified: true,
    views: 2800,
    bids: 35,
    collection: 'Degen Doges',
    model: 'Legendary',
    backdrop: 'Moon Base'
  },
  {
    id: '8',
    title: 'Space Explorer #042',
    subtitle: '#008',
    description: 'Космический исследователь из лимитированной серии. Включает доступ к метавселенной SpaceDAO.',
    price: 22.0,
    currency: 'TON',
    image: '/images/8.jpg',
    owner: 'EQI...s3t',
    verified: true,
    views: 1900,
    bids: 24,
    collection: 'Space Explorers',
    model: 'Epic',
    backdrop: 'Galaxy'
  },
  {
    id: '9',
    title: 'Crypto Skull #666',
    subtitle: '#009',
    description: 'Редкий Crypto Skull с анимированным пламенем. Номер 666 — самый востребованный в коллекции.',
    price: 18.7,
    currency: 'TON',
    image: '/images/9.jpg',
    owner: 'EQJ...t4u',
    verified: true,
    views: 1600,
    bids: 21,
    collection: 'Crypto Skulls',
    model: 'Epic',
    backdrop: 'Hellfire'
  },
  {
    id: '10',
    title: 'Genesis Block #001',
    subtitle: '#010',
    description: 'NFT, созданный в честь генезис-блока TON. Уникальный 1/1 артефакт с историческим значением.',
    price: 45.0,
    currency: 'TON',
    image: '/images/10.jpg',
    owner: 'EQK...u5v',
    verified: true,
    views: 4500,
    bids: 58,
    collection: 'TON Genesis',
    model: 'Mythic',
    backdrop: 'Blockchain'
  },
  {
    id: '11',
    title: 'AI Artist #128',
    subtitle: '#011',
    description: 'Генеративное искусство, созданное нейросетью. Каждый NFT уникален и не повторяется.',
    price: 9.5,
    currency: 'TON',
    image: '/images/11.jpg',
    owner: 'EQL...v6w',
    verified: true,
    views: 780,
    bids: 10,
    collection: 'AI Art',
    model: 'Rare',
    backdrop: 'Neural Network'
  },
  {
    id: '12',
    title: 'Neon Samurai #099',
    subtitle: '#012',
    description: 'Киберпанк-самурай с плазменной катаной. Часть коллаборации с известным японским художником.',
    price: 14.2,
    currency: 'TON',
    image: '/images/12.jpg',
    owner: 'EQM...w7x',
    verified: true,
    views: 1100,
    bids: 14,
    collection: 'Neon Warriors',
    model: 'Epic',
    backdrop: 'Neo Tokyo'
  },
  {
    id: '13',
    title: 'Diamond Hands #420',
    subtitle: '#013',
    description: 'Символ крипто-культуры. Холдеры с Diamond Hands получают приоритет в whitelist новых проектов.',
    price: 11.8,
    currency: 'TON',
    image: '/images/13.jpg',
    owner: 'EQN...x8y',
    verified: true,
    views: 920,
    bids: 12,
    collection: 'Diamond Hands',
    model: 'Rare',
    backdrop: 'Trading Floor'
  },
  {
    id: '14',
    title: 'Wizard of DeFi #256',
    subtitle: '#014',
    description: 'Магический NFT из коллекции DeFi Wizards. Даёт буст к yield farming в партнёрских протоколах.',
    price: 13.5,
    currency: 'TON',
    image: '/images/14.jpg',
    owner: 'EQO...y9z',
    verified: true,
    views: 1050,
    bids: 13,
    collection: 'DeFi Wizards',
    model: 'Epic',
    backdrop: 'Magic Tower'
  },
  {
    id: '15',
    title: 'Shadow Ninja #088',
    subtitle: '#015',
    description: 'Теневой ниндзя с невидимым клинком. Один из 100 с атрибутом "Invisible Blade".',
    price: 10.3,
    currency: 'TON',
    image: '/images/15.jpg',
    owner: 'EQP...z0a',
    verified: true,
    views: 850,
    bids: 11,
    collection: 'Shadow Clan',
    model: 'Rare',
    backdrop: 'Midnight'
  },
  {
    id: '16',
    title: 'Robo Warrior #512',
    subtitle: '#016',
    description: 'Боевой робот из вселенной MechaBattle. Используется в P2E игре с призовым фондом.',
    price: 7.9,
    currency: 'TON',
    image: '/images/16.jpg',
    owner: 'EQQ...a1b',
    verified: true,
    views: 690,
    bids: 9,
    collection: 'MechaBattle',
    model: 'Rare',
    backdrop: 'Arena'
  },
  {
    id: '17',
    title: 'Viking Lord #333',
    subtitle: '#017',
    description: 'Легендарный викинг с молотом Тора. Топ-50 по редкости среди 5,000 NFT коллекции.',
    price: 16.0,
    currency: 'TON',
    image: '/images/17.jpg',
    owner: 'EQR...b2c',
    verified: true,
    views: 1300,
    bids: 17,
    collection: 'Viking Lords',
    model: 'Epic',
    backdrop: 'Valhalla'
  },
  {
    id: '18',
    title: 'Android X #1024',
    subtitle: '#018',
    description: 'Продвинутый андроид с квантовым процессором. Часть метавселенной Android Universe.',
    price: 19.5,
    currency: 'TON',
    image: '/images/18.jpg',
    owner: 'EQS...c3d',
    verified: true,
    views: 1750,
    bids: 22,
    collection: 'Android X',
    model: 'Epic',
    backdrop: 'Cyber Lab'
  },
  {
    id: '19',
    title: 'Wild West #199',
    subtitle: '#019',
    description: 'Легендарный стрелок Дикого Запада. NFT даёт доступ к эксклюзивным турнирам в игре.',
    price: 12.0,
    currency: 'TON',
    image: '/images/19.jpg',
    owner: 'EQT...d4e',
    verified: true,
    views: 980,
    bids: 13,
    collection: 'Wild West',
    model: 'Rare',
    backdrop: 'Desert Town'
  },
  {
    id: '20',
    title: 'Pharaoh Gold #050',
    subtitle: '#020',
    description: 'Золотой фараон из лимитированной египетской серии. Всего 100 штук в существовании.',
    price: 14.8,
    currency: 'TON',
    image: '/images/20.jpg',
    owner: 'EQU...e5f',
    verified: true,
    views: 1150,
    bids: 15,
    collection: 'Ancient Egypt',
    model: 'Epic',
    backdrop: 'Pyramid'
  },
  {
    id: '21',
    title: 'Super Hero #2048',
    subtitle: '#021',
    description: 'Супергерой с уникальной способностью телепортации. Редкость: менее 2% коллекции.',
    price: 8.5,
    currency: 'TON',
    image: '/images/21.jpg',
    owner: 'EQV...f6g',
    verified: true,
    views: 720,
    bids: 9,
    collection: 'Super Heroes',
    model: 'Rare',
    backdrop: 'Metropolis'
  },
  {
    id: '22',
    title: 'Dragon Emperor #007',
    subtitle: '#022',
    description: 'Императорский дракон с золотой чешуёй. Один из 10 легендарных драконов в коллекции.',
    price: 35.0,
    currency: 'TON',
    image: '/images/22.jpeg',
    owner: 'EQW...g7h',
    verified: true,
    views: 3100,
    bids: 40,
    collection: 'Dragon Empire',
    model: 'Mythic',
    backdrop: 'Volcano'
  },
  {
    id: '23',
    title: 'Ghost Protocol #404',
    subtitle: '#023',
    description: 'Анимированный призрак из серии Ghost Protocol. Номер 404 — отсылка к интернет-культуре.',
    price: 17.5,
    currency: 'TON',
    image: '/images/23.gif',
    owner: 'EQX...h8i',
    verified: true,
    views: 1400,
    bids: 18,
    collection: 'Ghost Protocol',
    model: 'Epic',
    backdrop: 'Haunted Castle'
  },
  {
    id: '24',
    title: 'Rainbow Unicorn #111',
    subtitle: '#024',
    description: 'Радужный единорог с анимированной гривой. Приносит удачу холдерам — доказано статистикой.',
    price: 29.0,
    currency: 'TON',
    image: '/images/24.gif',
    owner: 'EQY...i9j',
    verified: true,
    views: 2600,
    bids: 33,
    collection: 'Magic Creatures',
    model: 'Legendary',
    backdrop: 'Rainbow Sky'
  },
  {
    id: '25',
    title: 'Phoenix Rising #001',
    subtitle: '#025',
    description: 'Genesis Phoenix — первый в коллекции. Символ возрождения и нового начала в крипто.',
    price: 42.0,
    currency: 'TON',
    image: '/images/25.webp',
    owner: 'EQZ...j0k',
    verified: true,
    views: 4200,
    bids: 55,
    collection: 'Phoenix Rising',
    model: 'Mythic',
    backdrop: 'Eternal Flame'
  },
  {
    id: '26',
    title: 'Yeti Alpha #069',
    subtitle: '#026',
    description: 'Альфа-йети из снежных гор. Холдеры получают доступ к закрытому Discord-сообществу.',
    price: 21.0,
    currency: 'TON',
    image: '/images/26.png',
    owner: 'EQA...k1l',
    verified: true,
    views: 1850,
    bids: 23,
    collection: 'Yeti Club',
    model: 'Epic',
    backdrop: 'Ice Mountain'
  },
  {
    id: '27',
    title: 'Kraken Deep #008',
    subtitle: '#027',
    description: 'Глубоководный кракен с биолюминесценцией. Один из 8 легендарных морских существ.',
    price: 38.0,
    currency: 'TON',
    image: '/images/27.jpg',
    owner: 'EQB...l2m',
    verified: true,
    views: 3500,
    bids: 45,
    collection: 'Deep Sea',
    model: 'Mythic',
    backdrop: 'Abyss'
  },
  {
    id: '28',
    title: 'Goblin Trader #999',
    subtitle: '#028',
    description: 'Гоблин-трейдер с золотыми монетами. Символ успешной торговли в NFT-сообществе.',
    price: 11.0,
    currency: 'TON',
    image: '/images/28.jpeg',
    owner: 'EQC...m3n',
    verified: true,
    views: 890,
    bids: 11,
    collection: 'Goblin Market',
    model: 'Rare',
    backdrop: 'Trading Cave'
  },
  {
    id: '29',
    title: 'Elf Archer #314',
    subtitle: '#029',
    description: 'Эльфийский лучник с магическим луком. Число Pi в номере — для ценителей математики.',
    price: 24.5,
    currency: 'TON',
    image: '/images/29.jpg',
    owner: 'EQD...n4o',
    verified: true,
    views: 2200,
    bids: 28,
    collection: 'Elven Kingdom',
    model: 'Legendary',
    backdrop: 'Enchanted Forest'
  },
  {
    id: '30',
    title: 'Bridge Troll #100',
    subtitle: '#030',
    description: 'Страж моста из коллекции Fantasy Guardians. Даёт скидку на комиссии в партнёрских DEX.',
    price: 15.5,
    currency: 'TON',
    image: '/images/30.jpeg',
    owner: 'EQE...o5p',
    verified: true,
    views: 1200,
    bids: 16,
    collection: 'Fantasy Guardians',
    model: 'Epic',
    backdrop: 'Stone Bridge'
  }
];